### ISSUE TITLE
Correlation function continued

### ISSUE THREAD

**Issue by jhnnsnk** [INM-6/mesocircuit-model#224]
As a follow-up to #223, double check time lags and scaling of cross-correlation functions.

**Comment by espenhgn** [comment]
Hi Johanna,
On this line: https://github.com/INM-6/mesocircuit-model/blob/ed1baa417f926e4596eb9a121b04f413ba5a779c/scripts/ms_figures_cross_correlation_function.py#L138C55-L138C62
the code does not account for the downsampling factor `q`, as `lags=25` I assume must be in units of ms, while the output of `ss.correlation_lags` is in units of dt.

**Comment by jhnnsnk** [comment]
Well spotted @espenhgn! #225 converts the lags into time units (ms).
